spring.application.name=project


spring.datasource.url=jdbc:postgresql://ep-noisy-darkness-a1qnjfhd-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Y36lspXzhBvu&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Y36lspXzhBvu
jwt.secret=PHUNGTHANHDO-HFUIASDUFAHUSDFHUASUIDFHASDUIFASHDF
jwt.expiration=3600000

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.enabled=false
